name: flutter_application_2
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State management
  provider: ^6.1.2

  # UI/Utils
  cupertino_icons: ^1.0.8
  qr_flutter: ^4.1.0
  cached_network_image: ^3.4.1
  intl: ^0.19.0

  # Local storage
  shared_preferences: ^2.3.2

  # Firebase
  firebase_core: ^3.5.0
  cloud_firestore: ^5.5.0
  firebase_auth: ^5.3.1
  firebase_storage: ^12.3.1     # << สำหรับอัปโหลดสลิป

  # Upload from device (ถ้าใช้ file_picker เป็นหลัก จะไม่ต้องใช้ image_picker ก็ได้)
  image_picker: ^1.1.2
  file_picker: ^8.1.2           # << เลือกไฟล์สลิปได้ทั้ง Android/iOS/Web

  # ---- GPS Order Tracking ----
  geolocator: ^11.1.0
  permission_handler: ^11.3.1

  # ---- OpenStreetMap via flutter_map ----
  flutter_map: ^6.1.0
  latlong2: ^0.9.1

  # ---- Routing / Polyline (OSRM, etc.) ----
  http: ^1.2.2

  # (ถ้าไม่ใช้ Supabase แล้ว ลบบรรทัดนี้ออกได้)
  supabase_flutter: ^2.4.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/qr/qr_promptpay_kplus.jpg
    # ถ้าไฟล์จริงเป็น .png ให้เปลี่ยนชื่อให้ตรง เช่น:
    # - assets/qr/qr_promptpay_kplus.png
