name: flutter_application_2
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State management
  provider: ^6.1.2

  # UI/Utils
  cupertino_icons: ^1.0.8
  qr_flutter: ^4.1.0
  cached_network_image: ^3.4.1
  intl: ^0.19.0

  # Local storage
  shared_preferences: ^2.3.2

  # Firebase
  firebase_core: ^3.5.0
  cloud_firestore: ^5.5.0
  firebase_auth: ^5.3.1

  # (ถ้าเลิกใช้ Supabase แล้ว สามารถลบบรรทัดนี้ได้)
  supabase_flutter: ^2.4.8

  # อัปโหลดรูปจากเครื่อง
  image_picker: ^1.1.2

  # ---- GPS Order Tracking ----
  geolocator: ^11.1.0
  permission_handler: ^11.3.1

  # ---- OpenStreetMap via flutter_map ----
  flutter_map: ^6.1.0
  latlong2: ^0.9.1

  # ---- Routing / Polyline (OSRM, etc.) ----
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  # assets:
  #   - assets/images/
  #   - assets/icons/
