name: flutter_application_2
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"   # ✅ ต้องเป็นช่วงเวอร์ชัน ไม่ใช่ ^

dependencies:
  flutter:
    sdk: flutter

  # State management
  provider: ^6.1.2

  # UI/Utils
  cupertino_icons: ^1.0.8
  qr_flutter: ^4.1.0
  cached_network_image: ^3.4.1

  # Firebase (ใช้ Firestore เก็บข้อมูล + Auth สำหรับผู้ใช้)
  firebase_core: ^3.5.0
  cloud_firestore: ^5.4.4
  firebase_auth: ^5.3.1      # ✅ เพิ่มเพื่อผูกข้อมูลกับ uid ของผู้ใช้

  # Supabase (เก็บรูป & public URL)
  supabase_flutter: ^2.4.8

  # (ถ้าแอดมินจะอัปโหลดรูปจากเครื่อง)
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  # assets:
  #   - assets/images/
  #   - assets/icons/
