name: flutter_application_2
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"   # ต้องเป็นช่วงเวอร์ชัน

dependencies:
  flutter:
    sdk: flutter

  # State management
  provider: ^6.1.2

  # UI/Utils
  cupertino_icons: ^1.0.8
  qr_flutter: ^4.1.0
  cached_network_image: ^3.4.1
  intl: ^0.19.0

  # Local storage (ใช้กับหน้า บันทึกรายจ่ายง่ายๆ)
  shared_preferences: ^2.3.2

  # Firebase
  firebase_core: ^3.5.0
  cloud_firestore: ^5.4.4
  firebase_auth: ^5.3.1

  # Supabase (เก็บรูป & public URL)
  supabase_flutter: ^2.4.8

  # อัปโหลดรูปจากเครื่อง
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true