// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJDAYRGyRumsgcZHEQgoKqnwRx7ip3C7k',
    appId: '1:112753720419:web:f646ca654b3ab9dd894c56',
    messagingSenderId: '112753720419',
    projectId: 'my-project-e3079',
    authDomain: 'my-project-e3079.firebaseapp.com',
    storageBucket: 'my-project-e3079.firebasestorage.app',
    measurementId: 'G-NRVZPP0CMC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhGXz6umvMNnyx6iYO9rl3ZN79296zHpg',
    appId: '1:112753720419:android:7bfc5c0bebdb6447894c56',
    messagingSenderId: '112753720419',
    projectId: 'my-project-e3079',
    storageBucket: 'my-project-e3079.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4vL_cZOYctLcWdUwE4AX13hjwB5f6WsI',
    appId: '1:112753720419:ios:81eb70085e5b81ba894c56',
    messagingSenderId: '112753720419',
    projectId: 'my-project-e3079',
    storageBucket: 'my-project-e3079.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4vL_cZOYctLcWdUwE4AX13hjwB5f6WsI',
    appId: '1:112753720419:ios:81eb70085e5b81ba894c56',
    messagingSenderId: '112753720419',
    projectId: 'my-project-e3079',
    storageBucket: 'my-project-e3079.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJDAYRGyRumsgcZHEQgoKqnwRx7ip3C7k',
    appId: '1:112753720419:web:0072ed2975ec73a6894c56',
    messagingSenderId: '112753720419',
    projectId: 'my-project-e3079',
    authDomain: 'my-project-e3079.firebaseapp.com',
    storageBucket: 'my-project-e3079.firebasestorage.app',
    measurementId: 'G-1XF5W83DK6',
  );
}
